### PR TITLE
Autogenes updates

### PR DESCRIPTION
**Pull request by LorenzoMerotto**
Update of AutogeneS following authors requirements

### CODE REVIEW

**Comment by LorenzoMerotto** [comment]
@grst I made some slight changes to a function and I get errors that I never saw before. 
Do you have an idea of what's happening here?

**Comment by grst** [comment]
Ok, so the actual error is 
```
2022-09-02T11:24:13.4456358Z ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/runner/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-38-x86_64-linux-gnu.so)
```

and is likely due to some version conflicts in the conda environment created by reticulate. 
Can you remind me where those python dependencies are declared?

**Comment by LorenzoMerotto** [comment]
The Python dependencies are imported inside the AutogeneS functions, if this is what you mean

**Comment by grst** [comment]
i tried just setting the miniconda python version to 3.9 

if that doesn't happen to work, we would need to install the [compilers](https://anaconda.org/conda-forge/compilers) conda package in that miniconda environment.

**Comment by LorenzoMerotto** [comment]
@grst the problem is that locally everything works. The issue arises when the tests are run on GitHub

**Comment by grst** [comment]
You could also just update the test to whatever autogenes produces now. 
The main purpose of this test is basically to get notified when a method suddenly produces a different output - in this case it is intentional, so all good.

**Pull request merged**
