### PR TITLE
update reticulate config

### PR DESCRIPTION
**Pull request by LorenzoMerotto**
Updated the reticulate/Python packages configuration acording to [doc](https://rstudio.github.io/reticulate/articles/python_dependencies.html#manual-configuration) so that a Python environment is created once and for all when the package is installed

This is just a test to see if we have more luck with the automated tests

### CODE REVIEW

**Comment by LorenzoMerotto** [comment]
@alex-d13 look at this lol 
Hopefully I fixed all the Python issues

**Comment by LorenzoMerotto** [comment]
Hello @grst 

After some work, I'd like to propose you this alternative python setup for omnideconv. 
In the previous version python was initialized when a python-based method was called, and this was done trough several `method_checkload()` functions, as you can see [here](https://github.com/omnideconv/omnideconv/blob/42e2984b002dda13881005ed8a2fc96fba42d9e6/R/AutoGeneS.R#L280). 
However this led to various errors during the tests with the various conda environments as the one that you can see in #138 now. 

What I did was introducing the creation of a new conda environment, created when the package is first installed and loaded. All the necessary python packages are installed in this `r-omnideconv` environment. This should make the whole reticulate management a bit easier. 

What do you think about it? Also tagging @PelzKo

**Comment by grst** [comment]
sounds good to me! Isn't this somewhat similar to the [basilisk](https://bioconductor.org/packages/release/bioc/html/basilisk.html) approach of bioconductor?

**Comment by LorenzoMerotto** [comment]
@grst I think so! @federicomarini mentioned this basilisk approach as well, but I'm not so familiar with it.

**Comment by federicomarini** [comment]
There's a pretty informative vignette for it on how to get it work in package contexts.

And very much in the spirit of "use the ~~f~~source, Luke", maybe you can find excellent implementations in any of the package that import that one.

image

To browse the code directly for those packages, a nice yet probably unappreciated gem is this: https://code.bioconductor.org/

**Comment by LorenzoMerotto** [comment]
Now all the tests are passing. Waiting for @PelzKo opinion on this, then we can hopefully merge!

**Comment by PelzKo** [comment]
Looks good to me!

**Pull request merged**
