### PR TITLE
Cleanup imports

### PR DESCRIPTION
**Pull request by federicomarini**
After a discussion with @constantin-zackl , here's directly a compact PR replacing the imports.
Since I am missing some installation components, I could not test it on my own machine.
Can someone of you with a full install give it a quick R CMD check spin? Thanks!

### CODE REVIEW

**Comment by federicomarini** [comment]
... or I guess I will let the CI do its job 😉

**Comment by federicomarini** [comment]
Green light till now.
So, while we are at it: do we need `snowfall` as depends? It is also listed as imports. This triggers a note in R CMD check

**Comment by grst** [comment]
There was something here:
https://github.com/omnideconv/omnideconv/pull/112

@alex-d13, do we need it eventually?

**Comment by federicomarini** [comment]
a better question is "where do we need it", because it is at least an import. But currently it is listed twice in the DESCRIPTION

**Comment by alex-d13** [comment]
yes, its an import of bayesprism. I remember that i had issues with this package when i did not import it in the namespace directly.
Let me check if thats still the case, otherwise we can remove it and only keep it in the DESCRIPTION

**Comment by alex-d13** [comment]
So apparently this is a known issue of snowfall (https://stackoverflow.com/questions/68145132/error-in-setdefaultclusteroptionstype-sfoptiontype-could-not-find-functio)
when i remove it from the `DEPENDS` section, the bayesprism test fails with the same error as in the stackoverflow post, even though i have added it as an `@import` above the `deconvolute_bayesprism` function as well.

Do you have any other workaround we could try?

**Comment by federicomarini** [comment]
Not really, but this is "secondary".
For the purpose of this PR, I would propose we simply keep `snowfall` as Depends, and remove it as an Imports.
@grst good for you as well?

**Pull request merged**
